language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy
  - pypy-5.3
  - pypy3
  - pypy3.3-5.2-alpha1
matrix:
  allow_failures:
    - python: nightly
install:
  - pip install flake8==2.1.0 git+https://github.com/PyCQA/pep8
  - python setup.py install
  - pip list
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 --version; fi
script:
  - python setup.py test -q
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then flake8 pyflakes setup.py; fi
sudo: false
