language: python
cache: pip
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy
    - python: pypy-5.3
    - python: pypy3
    - python: 3.7
      dist: xenial
    - python: nightly
      dist: xenial
install:
  - pip install --upgrade .
  - pip list
script:
  - python setup.py test -q
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then pip install flake8==3.6.0 pycodestyle==2.4.0 && flake8 --version && flake8 pyflakes setup.py; fi
